# Dockerfile
FROM eclipse-mosquitto:2.0.18
LABEL maintainer "maag.matthias@googlemail.com"
LABEL description "Mosquitto with config file"
COPY mosquitto.conf /mosquitto/config/mosquitto.conf
EXPOSE 1883